=== connectis/ricestat/webci.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation= "http://ws.webci.it/ http://ws.webci.it/webci.xsd">
    <xs:element name="MTO_SchedineRQ" >
        <xs:complexType>
            <xs:sequence>
                <xs:element name="POS" type="POSType" />
                <xs:choice>
                    <xs:element name="InserimentoAlloggiati"  type="InserimentoAlloggiatiType" />
                    <xs:element name="Aggiornamento"  type="AggiornamentoType"/>
                    <xs:element name="Eliminazione" type="EliminazioneType" />    
                    <xs:element name="RequestSegments" type="RequestSegmentsType" />
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element> 

    <xs:complexType name="POSType"  >
        <xs:annotation>
            <xs:documentation>Point of Sale (POS) is the details identifying the party or PMS making the request.</xs:documentation>
        </xs:annotation>    
        <xs:sequence>
            <xs:element name="Source" type="SourceType" minOccurs="2" maxOccurs="2">
                <xs:annotation>
                    <xs:documentation>This holds details regarding the requestor. It may be repeated to also accommodate the delivery systems.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
       
    <xs:complexType name="SourceType" >
        <xs:sequence>
            <xs:element name="RequestorID"  >
                <xs:complexType>
                    <xs:annotation>
                        <xs:documentation>An identifier of the entity making the request </xs:documentation>
                    </xs:annotation>
                    <xs:attributeGroup ref="Authentication"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:attributeGroup name="Authentication">
        <xs:attribute name="Type" use="required" type="xs:string" />
        <xs:attribute name="ID" use="required" type="xs:string" />
        <xs:attribute name="MessagePassword" use="required" type="xs:string" />
    </xs:attributeGroup>

    <xs:complexType name="EliminazioneType" >
        <xs:sequence>
            <xs:element name="Alloggiato">
                <xs:complexType>
                    <xs:attribute name="Id" use="required" type="xs:string" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType> 
     
    <xs:complexType  name="AggiornamentoType" >
        <xs:sequence>
            <xs:element name="Ospite" type="OspiteType" >  
            </xs:element>
        </xs:sequence>
    </xs:complexType > 

    <xs:complexType name="InserimentoAlloggiatiType" >
        <xs:choice>
            <xs:element  name="Gruppo" type="GruppoType"  minOccurs="2" maxOccurs="unbounded" />
            <xs:element name="OspiteSingolo" type="OspiteSingoloType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:attribute name="CodiceEsercizio"/>
    </xs:complexType>

    <xs:complexType name="RequestSegmentsType" >
        <xs:sequence>
            <xs:element name="RequestSegment" >
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="SearchCriteria" >
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="Criterion" >
                                        <xs:complexType>
                                            <xs:choice>
                                                <xs:element name="DateRange"  type="DateRangeType" />
                                                <xs:element name="UniqueID" type="UniqueIDType" />
                                                <xs:element name="ImpostaSoggiorno" type="ImpostaSoggiornoType" />
                                                <xs:element name="ListaResidenze" type="ListaResidenzeType" />
                                                <xs:element name="ListaStatistiche" type="ListaStatisticheType" />
                                            </xs:choice>
                                        </xs:complexType>
                                    </xs:element>  
                                </xs:sequence>
                            </xs:complexType>  	
                        </xs:element>
                    </xs:sequence>
                </xs:complexType> 
            </xs:element> 
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DateRangeType" >       
        <xs:attribute name="Start" use="required"  type="xs:date">
            <xs:annotation>
                <xs:documentation> Data di inizio periodo di ricerca (aaaa-mm-gg)</xs:documentation>
            </xs:annotation>
        </xs:attribute> 
        <xs:attribute name="End" use="required"  type="xs:date">
            <xs:annotation>
                <xs:documentation> Data di fine periodo di ricerca  (aaaa-mm-gg)</xs:documentation>
            </xs:annotation>
        </xs:attribute>    
    </xs:complexType>

    <xs:complexType name="UniqueIDType" >
        <xs:attribute name="Id" use="required"  type="xs:string">
            <xs:annotation>
                <xs:documentation>Identificativo univoco</xs:documentation>
            </xs:annotation>
        </xs:attribute> 
        <xs:attribute name="tipo" use="required">
            <xs:annotation>
                <xs:documentation>Tipo di identificativo (Gruppo; OspiteSingolo)</xs:documentation>
            </xs:annotation>
            <xs:simpleType> 
                <xs:restriction base="xs:string">
                    <xs:enumeration value="Gruppo" />
                    <xs:enumeration value="OspiteSingolo" />
                </xs:restriction>
            </xs:simpleType> 
        </xs:attribute> 
    </xs:complexType>
  
    <xs:complexType name="ImpostaSoggiornoType" >
        <xs:attribute name="Comune" use="required"  type="xs:int">
            <xs:annotation>
                <xs:documentation>Codice identificativo univoco del comune</xs:documentation>
            </xs:annotation>
        </xs:attribute> 
    </xs:complexType>

    <xs:complexType name="ListaResidenzeType" >
        <xs:attribute name="tipo" use="required" >
            <xs:annotation>
                <xs:documentation>Tipo di identificativo (Stati; Comuni)</xs:documentation>
            </xs:annotation>
            <xs:simpleType> 
                <xs:restriction base="xs:string">
                    <xs:enumeration value="Stati" />
                    <xs:enumeration value="Comuni" />
                </xs:restriction>
            </xs:simpleType> 
        </xs:attribute> 
    </xs:complexType>
    <xs:complexType name="ListaStatisticheType" >
        <xs:attribute name="tipo" use="required" >
            <xs:annotation>
                <xs:documentation>Tipo di identificativo (Stati; Comuni)</xs:documentation>
            </xs:annotation>
            <xs:simpleType> 
                <xs:restriction base="xs:string">
                    <xs:enumeration value="TipoTurismo" />
                    <xs:enumeration value="MezzoDiTrasporto" />
                    <xs:enumeration value="TipoPrenotazione" />
                </xs:restriction>
            </xs:simpleType> 
        </xs:attribute> 
    </xs:complexType>
  
    <xs:element name="Provenienza" >
        <xs:complexType>
            <xs:choice>
                <xs:element name="Italia" type="ItaliaType" />
                <xs:element name="Estero" type="EsteroType" />
            </xs:choice>
        </xs:complexType>
    </xs:element> 
    <xs:element name="Nascita" >
        <xs:complexType>
            <xs:choice>
                <xs:element  name="Italia" type="ItaliaType" />
                <xs:element name="Estero" type="EsteroType" />
            </xs:choice>
        </xs:complexType>
    </xs:element> 
    <xs:element name="Cittadinanza" >
        <xs:complexType>
            <xs:attribute name="Stato" use="required" type="xs:string" />
        </xs:complexType>
    </xs:element> 

    <xs:complexType name="ItaliaType">
        <xs:attribute name="CodiceComune" use="required" type="xs:string" />
        <xs:attribute name="Provincia" use="required" type="xs:string"/>
        <xs:attribute name="Stato" use="required" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="EsteroType" >
        <xs:attribute name="Stato" use="required" type="xs:string" />
    </xs:complexType>
  
    <xs:complexType name="GruppoType">
        <xs:sequence>
            <xs:element name="Ospite" type="OspiteType" minOccurs="1"  >
               
            </xs:element>
  
            <xs:element name="Ospite" type="OspiteType" minOccurs="1" >
                <xs:annotation>
                    <xs:documentation>TipoAlloggiato solo Familiare (19) o Membro di gruppo (20)</xs:documentation>
                </xs:annotation>
                
            </xs:element>
        </xs:sequence>
        <xs:attribute name="IdGruppo" type="xs:ID"  use="required">
            <xs:annotation>
                <xs:documentation>Identificativo univoco del gruppo</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="OspiteSingoloType" >
        <xs:sequence>
            <xs:element name="Ospite" type="OspiteType" minOccurs="1" >        
                <xs:annotation>
                    <xs:documentation>TipoAlloggiato solo Ospite Singolo (16) </xs:documentation>
                </xs:annotation>     
                
            </xs:element>
        </xs:sequence>
		<xs:attribute name="Id" type="xs:string"  use="required"  >
            <xs:annotation>
                <xs:documentation>Identificativo univoco della movimentazione, non dell'utente, per utenti ricorrenti deve cambiare ogni volta</xs:documentation>
            </xs:annotation>
        </xs:attribute>

    </xs:complexType>

    <xs:complexType name="OspiteType" >
        <xs:sequence>        
            <xs:element ref="DataDiArrivo" minOccurs="1" />
            <xs:element ref="DataDiPartenza" minOccurs="1"  />
            <xs:element ref="DataDiNascita"  minOccurs="1" />
            <xs:element ref="Sesso" minOccurs="1"  />
            <xs:element ref="Provenienza" minOccurs="1" />
            <xs:element ref="Nascita" minOccurs="1" />
            <xs:element ref="Cittadinanza" minOccurs="1" />
            <xs:element ref="ImpostaDiSoggiorno"/>
            <xs:element ref="CampiStatistici"/>
            <xs:element name="Nome" type="xs:string"   minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Nome dell'ospite. OPZIONALE</xs:documentation>
                </xs:annotation>
            </xs:element> 
            <xs:element name="Cognome" type="xs:string"   minOccurs="0">
                <xs:annotation>
                    <xs:documentation>Cognome dell'ospite. OPZIONALE</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>        
        <xs:attribute name="Id" type="xs:string"  use="required"  >
            <xs:annotation>
                <xs:documentation>Identificativo univoco della movimentazione, non dell'utente, per utenti ricorrenti deve cambiare ogni volta</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="IdCamera" type="xs:string"  use="required"  >
            <xs:annotation>
                <xs:documentation>Identificativo univoco della camera (per il calcolo delle camere occupate)</xs:documentation>
            </xs:annotation>
        </xs:attribute>

                    <xs:attribute name="TipoAlloggiato">
                        <xs:simpleType> 
                            <xs:restriction base="xs:positiveInteger">
                                <xs:enumeration value="16"/>
                                <xs:enumeration value="17"/>
                                <xs:enumeration value="18"/>
                                <xs:enumeration value="19"/>
                                <xs:enumeration value="20"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute> 
                    <xs:attribute name="IdGruppo" type="xs:ID"  use="required">
                        <xs:annotation>
                            <xs:documentation>Possibilità di correggere gruppo</xs:documentation>
                        </xs:annotation>
                    </xs:attribute> 

    </xs:complexType>
    
    <xs:element name="DataDiArrivo"  type="xs:date">
        <xs:annotation>
            <xs:documentation> Data di arrivo (aaaa-mm-gg)</xs:documentation>
        </xs:annotation>
    </xs:element>
    
    <xs:element name="DataDiPartenza" type="xs:date">
        <xs:annotation>
            <xs:documentation> Data di partenza (aaaa-mm-gg)</xs:documentation>
        </xs:annotation>
    </xs:element>
  
    <xs:element name="DataDiNascita"  type="xs:date">
        <xs:annotation>
            <xs:documentation>Data di nascita (aaaa-mm-gg) </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="Sesso"   >
        <xs:annotation>
            <xs:documentation>Sesso (1=maschio; 2=femmina)</xs:documentation>
        </xs:annotation>
        <xs:simpleType> 
            <xs:restriction base="xs:positiveInteger">
                <xs:enumeration value="1" />
                <xs:enumeration value="2" />
            </xs:restriction>
        </xs:simpleType> 
    </xs:element>

    <xs:element name="ImpostaDiSoggiorno">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CodiceImpostaSoggiorno" type="xs:string"  >
                    <xs:annotation>
                        <xs:documentation>Codice per imposta di soggiorno, null se non esente</xs:documentation>
                    </xs:annotation>
                </xs:element> 
                <xs:element name="ValoreImpostaUnitaria" type="xs:decimal"  >
                    <xs:annotation>
                        <xs:documentation>Valore per singolo giorno dell'imposta</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="NottiImponibili" type="xs:positiveInteger"  >
                    <xs:annotation>
                        <xs:documentation>Notti soggette ad Imposta</xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="CampiStatistici" >
        <xs:complexType>
            <xs:sequence>
                <xs:element name="TipoTurismo" type="TipoTurismo" minOccurs="0" />
                <xs:element name="MezzoDiTrasporto" type="MezzoDiTrasporto" minOccurs="0" />
                <xs:element name="TipoPrenotazione" type="TipoPrenotazione" minOccurs="0" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
  
    <xs:simpleType name="TipoTurismo">
        <xs:restriction base="xs:string">
            <xs:enumeration  value="Affari/Congressuale" />
            <xs:enumeration  value="Arte e cultura" />
            <xs:enumeration  value="Cicloturismo" />
            <xs:enumeration  value="Enogastronomia" />
            <xs:enumeration  value="Fiere" />
            <xs:enumeration  value="Parchi Tematici" />
            <xs:enumeration  value="Religioso" />
            <xs:enumeration  value="Salute" />
            <xs:enumeration  value="Scolastico" />
            <xs:enumeration  value="Sportivo e Fitness" />
            <xs:enumeration  value="Terme" />
            <xs:enumeration  value="Altro" />
        </xs:restriction>
    </xs:simpleType>  

    <xs:simpleType name="MezzoDiTrasporto" >
        <xs:restriction base="xs:string">
            <xs:enumeration  value="Auto" />
            <xs:enumeration  value="Aereo" />
            <xs:enumeration  value="Treno" />
            <xs:enumeration  value="Autobus" />
            <xs:enumeration  value="Barca / Nave" />
            <xs:enumeration  value="Moto" />
            <xs:enumeration  value="Bicicletta" />
            <xs:enumeration  value="Altro" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TipoPrenotazione" >
        <xs:restriction base="xs:string">
            <xs:enumeration  value="Email" />
            <xs:enumeration  value="Sito web privato" />
            <xs:enumeration  value="Portale" />
            <xs:enumeration  value="Telefonica/Fax" />
            <xs:enumeration  value="Tour Operator" />
            <xs:enumeration  value="Altro" />
        </xs:restriction>
    </xs:simpleType>
  
</xs:schema>

=== connectis/ricestat/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<MTO_SchedineRQ xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/Users/andrea/Downloads/oxygen/Oxygen%20XML%20Editor.app/webci.xsd">
    <POS>
        <Source>
            <RequestorID Type="Type0" ID="ID0" MessagePassword="MessagePassword0"/>
        </Source>
    </POS>
    <POS>
        <Source>
            <RequestorID Type="Type1" ID="ID1" MessagePassword="MessagePassword1"/>
        </Source>
    </POS>
    <InserimentoAlloggiati>
        <Gruppo IdGruppo="ID000">
            <Ospite TipoAlloggiato="17" Id="ID001" IdCamera="IdCamera0">
                <DataDiArrivo>2006-05-04</DataDiArrivo>
                <DataDiPartenza>2006-05-04</DataDiPartenza>
                <DataDiNascita>2006-05-04</DataDiNascita>
                <Sesso>1</Sesso>
                <Provenienza>
                    <Italia CodiceComune="50" Provincia="50" Stato="50"/>
<!--                    <Estero Stato="50"/>-->
                </Provenienza>
                <Nascita>
                    <Italia CodiceComune="50" Provincia="50" Stato="50"/>
<!--                    <Estero Stato="50"/>-->
                </Nascita>
                <Cittadinanza Stato="50"/>
                <ImpostaDiSoggiorno>
                    <CodiceImpostaSoggiorno>CodiceImpostaSoggiorno0</CodiceImpostaSoggiorno>
                    <ValoreImpostaUnitaria>0</ValoreImpostaUnitaria>
                    <NottiImponibili>50</NottiImponibili>
                </ImpostaDiSoggiorno>
                <CampiStatistici TipoTurismo="Affari/Congressuale" MezzoDiTrasporto="Auto" TipoPrenotazione="Email"/>
            </Ospite>
        </Gruppo>
        <Gruppo IdGruppo="ID002">
            <Ospite TipoAlloggiato="17" Id="ID003" IdCamera="IdCamera1">
                <DataDiArrivo>2006-05-04</DataDiArrivo>
                <DataDiPartenza>2006-05-04</DataDiPartenza>
                <DataDiNascita>2006-05-04</DataDiNascita>
                <Sesso>1</Sesso>
                <Provenienza>
                    <Italia CodiceComune="50" Provincia="50" Stato="50"/>
<!--                    <Estero Stato="50"/>-->
                </Provenienza>
                <Nascita>
                    <Italia CodiceComune="50" Provincia="50" Stato="50"/>
<!--                    <Estero Stato="50"/>-->
                </Nascita>
                <Cittadinanza Stato="50"/>
                <ImpostaDiSoggiorno>
                    <CodiceImpostaSoggiorno>CodiceImpostaSoggiorno1</CodiceImpostaSoggiorno>
                    <ValoreImpostaUnitaria>0</ValoreImpostaUnitaria>
                    <NottiImponibili>50</NottiImponibili>
                </ImpostaDiSoggiorno>
                <CampiStatistici TipoTurismo="Affari/Congressuale" MezzoDiTrasporto="Auto" TipoPrenotazione="Email"/>
            </Ospite>
        </Gruppo>
<!--        <OspiteSingolo>
            <Ospite TipoAlloggiato="16" Id="ID004" IdCamera="IdCamera2">
                <DataDiArrivo>2006-05-04</DataDiArrivo>
                <DataDiPartenza>2006-05-04</DataDiPartenza>
                <DataDiNascita>2006-05-04</DataDiNascita>
                <Sesso>1</Sesso>
                <Provenienza>
                    <Italia CodiceComune="50" Provincia="50" Stato="50"/>
                </Provenienza>
                <Nascita>
                    <Italia CodiceComune="50" Provincia="50" Stato="50"/>
                </Nascita>
                <Cittadinanza Stato="50"/>
                <ImpostaDiSoggiorno>
                    <CodiceImpostaSoggiorno>CodiceImpostaSoggiorno2</CodiceImpostaSoggiorno>
                    <ValoreImpostaUnitaria>0</ValoreImpostaUnitaria>
                    <NottiImponibili>50</NottiImponibili>
                </ImpostaDiSoggiorno>
                <CampiStatistici TipoTurismo="Affari/Congressuale" MezzoDiTrasporto="Auto" TipoPrenotazione="Email"/>
            </Ospite>
        </OspiteSingolo>-->
    </InserimentoAlloggiati>
<!--    <Aggiornamento>
        <Ospite Id="ID005" IdCamera="IdCamera3">
            <DataDiArrivo>2006-05-04</DataDiArrivo>
            <DataDiPartenza>2006-05-04</DataDiPartenza>
            <DataDiNascita>2006-05-04</DataDiNascita>
            <Sesso>1</Sesso>
            <Provenienza>
                <Italia CodiceComune="50" Provincia="50" Stato="50"/>
            </Provenienza>
            <Nascita>
                <Italia CodiceComune="50" Provincia="50" Stato="50"/>
            </Nascita>
            <Cittadinanza Stato="50"/>
            <ImpostaDiSoggiorno>
                <CodiceImpostaSoggiorno>CodiceImpostaSoggiorno3</CodiceImpostaSoggiorno>
                <ValoreImpostaUnitaria>0</ValoreImpostaUnitaria>
                <NottiImponibili>50</NottiImponibili>
            </ImpostaDiSoggiorno>
            <CampiStatistici TipoTurismo="Affari/Congressuale" MezzoDiTrasporto="Auto" TipoPrenotazione="Email"/>
        </Ospite>
    </Aggiornamento>-->
<!--    <Eliminazione>
        <Alloggiato id="id0"/>
    </Eliminazione>-->
<!--    <RequestSegments>
        <RequestSegment>
            <SearchCriteria>
                <Criterion>
                </Criterion>
                <DateRange Start="2006-05-04" End="2006-05-04"/>
            </SearchCriteria>
        </RequestSegment>
    </RequestSegments>-->
</MTO_SchedineRQ>
